### ISSUE TITLE
Remove @mention in dota-changelogs

### ISSUE THREAD

**Issue by Z3nsay** [DulliAG/D2PB#10]
The bot correctly mentions the users when posting patches and patchnotes, but since the patchnotes are very long and most people read them on the website, they dont read it on discord. This causes mentions to stack up in long texts and makes it inconvenient for users who prefer to have no unread notifications.

Remove the mention of the user in #dota-changelogs. They still get the notification from #dota-updates and can manually check the changelogs without having to have a notification there too.

**Comment by tklein1801** [comment]
Users shouldn't get mentioned in the changelings anymore.
