### ISSUE TITLE
Double post 12.10.22 18:55

### ISSUE THREAD

**Issue by Z3nsay** [DulliAG/D2PB#16]
Gestern hat der Post zwei Updates um wiederholt gepostet, die auf den selben Link verweisen.
Wenn der die Ursache mit dem Provider "the loadout" zusammenhängen könnte, können wir den auch rausfiltern um somit eine einfachere Lösung zu haben.

**Comment by tklein1801** [comment]
Moin, der Patch dafür wurde noch gestern Abend unter der Version [v2.0.1](https://github.com/DulliAG/D2PB/releases/tag/v2.0.1) veröffentlicht.
