### ISSUE TITLE
Bot posts some updates twice

### ISSUE THREAD

**Issue by Z3nsay** [DulliAG/D2PB#17]
Occured once in Nov 4th at 13:05 a clock and 20:45 a clock.
Also 30th and 31th of Oct had some double posts.
Is it maybe an issue caused by multiple updates in the same day?

**Comment by tklein1801** [comment]
https://hrzfbjovxgyhsrevsuev.supabase.co/storage/v1/object/public/638716e6-652f-479b-b470-a7634cd75e37/ShareX/WindowsTerminal_nrafy11lmA.png

**Comment by tklein1801** [comment]
Er postet die News doppelt wenn das prüfen auf neue Changelogs fehlschlägt 😄 
Das Problem wurde behoben dadurch dass ab sofort kein NULL mehr zurück gegeben wird.
Mich wundert es lediglich dass überhaupt kein Treffer gefunden wurde, da die Liste auf jeden Fall immer mehr als 0 Einträge vorzuweisen hatte. Ich muss mal schauen wie sich das auf das veröffentlichen von den Changelog-Benachrichtigungen auswirken wird, oder das weiterhin ohne Probleme nach dem Patch funktionieren wird.

https://hrzfbjovxgyhsrevsuev.supabase.co/storage/v1/object/public/638716e6-652f-479b-b470-a7634cd75e37/ShareX/WindowsTerminal_4wv5sFIKHD.png
