### ISSUE TITLE
Faster updates

### ISSUE THREAD

**Issue by Z3nsay** [DulliAG/D2PB#9]
The bot takes longer than competitors to post updates 

"Patchbot" was able to notice and post the patch of 24. Aug 2022 at 00:58, while the ZensaydotaBot postet it 32 minutes later at 01:30.

If Im not mistaken, the interval of the bot is set to 30 minutes. If we would lower it to 1 minute, we would be only 3 minutes slower than "Patchbot" which would be enough.

**Comment by tklein1801** [comment]
```json
 "background_tasks": {
      "FETCHING_PATCHES": {
        "enabled": true,
        "execution_pattern": "*/10 * * * *"
      },
      "FETCHING_NEWS": {
        "enabled": true,
        "execution_pattern": "*/10 * * * *"
      }
    }
```
Derzeit wird die Abfrage alle 10 Minuten ausgeführt. Ich habe die Zeit mal reduziert und schaue mal wie es nun laufen wird.
